service: popin-one-health-api
provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment:
    DB_HOST: ${file(./env.yml):${self:provider.stage}.DB_HOST}
    DB_USER: ${file(./env.yml):${self:provider.stage}.DB_USER}
    DB_PASS: ${file(./env.yml):${self:provider.stage}.DB_PASS}
    DB_NAME: ${file(./env.yml):${self:provider.stage}.DB_NAME}
    DB_PORT: ${file(./env.yml):${self:provider.stage}.DB_PORT}
functions:
  getPofile:
    handler: src/handlers/getProfile.handler
    events:
      - http: 'GET /individual/{userProfile}/profile'
  getActivities:
    handler: src/handlers/getActivities.handler
    events:
      - http: 'GET /individual/{userProfile}/activities'
  getActivity:
    handler: src/handlers/getActivity.handler
    events:
      - http: 'GET /individual/{userProfile}/activities/{activityId}'
  getMeasurements:
    handler: src/handlers/getMeasurements.handler
    events:
      - http: 'GET /individual/{userProfile}/measurements'
  getMeasurement:
    handler: src/handlers/getMeasurement.handler
    events:
      - http: 'GET /individual/{userProfile}/measurements/{measurementId}'
  sandboxTestPost:
      handler: src/sandbox/testPost.handler
      events:
      - http: 'POST /sandbox/test-post'
  sandboxTestGet:
      handler: src/sandbox/testGet.handler
      events:
      - http: 'GET /sandbox/test-get'
plugins:
  - serverless-offline
