service: popin-one-health-api
provider:
  name: aws
  runtime: nodejs12.x
  stage: 'dev'
  region: us-east-1
functions:
  getPofile:
    handler: src/handlers/getProfile.handler
    events:
      - http: 'GET /individual/{userProfile}/profile'
  getActivities:
    handler: src/handlers/getActivities.handler
    events:
      - http: 'GET /individual/{userProfile}/activities'
  getActivity:
    handler: src/handlers/getActivity.handler
    events:
      - http: 'GET /individual/{userProfile}/activities/{activityId}'
  getMeasurements:
    handler: src/handlers/getMeasurements.handler
    events:
      - http: 'GET /individual/{userProfile}/measurements'
  getMeasurement:
    handler: src/handlers/getMeasurement.handler
    events:
      - http: 'GET /individual/{userProfile}/measurements/{measurementId}'
  sandboxTestPost:
      handler: src/sandbox/test-post.handler
      events:
      - http: 'POST /sandbox/test-post'
plugins:
  - serverless-offline
