service: popin-one-health-api
provider:
  name: aws
  runtime: nodejs12.x
  stage: 'dev'
  region: us-east-1
functions:
  getPofile:
    handler: src/handlers/get-profile.handler
    events:
      - http: 'GET /{userProfile}/profile'
  getActivities:
    handler: src/handlers/get-activities.handler
    events:
      - http: 'GET /{userProfile}/activities'
  getActivity:
    handler: src/handlers/get-activity.handler
    events:
      - http: 'GET /{userProfile}/activities/{activityId}'
  getMeasurements:
    handler: src/handlers/get-measurements.handler
    events:
      - http: 'GET /{userProfile}/measurements'
  getMeasurement:
    handler: src/handlers/get-measurement.handler
    events:
      - http: 'GET /{userProfile}/measurements/{measurementId}'
plugins:
  - serverless-offline
